<?php 

	$blog_home_visible = 3; // 3 posts visibles sur la page d'accueil

	$blog = [
		[
			'title' => 'Kaisen Linux 20191214 changelog',
			'extract' => 'First public release. First beta version. Over 100 integrated tools. A lot of sleepless nights. Alpha version.',
			'date'=> '2020/04/03',
			'visuel' => '/img/blog/screen20191214.png',
			'link' => 'kaisenlinux20191214.php',
			'author' => 'Kevin Chevreuil - Kaisen',
		],	
		[
			'title' => 'Kaisen Linux 20191229 Release Notes',
			'extract' => 'This version is the first version was the first version to be posted on the Kaisen Linux website. Amelioration of the 20191219 release.',
			'date'=> '2020/04/03',
			'visuel' => '/img/blog/screensr.png',
			'link' => 'kaisenlinux20191229.php',
			'author' => 'Kevin Chevreuil - Kaisen',
		],	
		[
			'title' => 'Kaisen Linux 20200114 Release Notes',
			'extract' => 'This new release is revision at 20191229 release. UEFI partial support. More features for live system. First beta version.',
			'date'=> '2020/04/03',
			'visuel' => '/img/blog/screensr.png',
			'link' => 'kaisenlinux20200114.php',
			'author' => 'Kevin Chevreuil - Kaisen',
		],	
		[
			'title' => 'Kaisen Linux 20200206 Release Notes',
			'extract' => 'This new release is revision of version 20200114. Full UEFI support. Fix importants bugs. Lots of new things.',
			'date'=> '2020/04/03',
			'visuel' => '/img/blog/screensr.png',
			'link' => 'kaisenlinux20200206.php',
			'author' => 'Kevin Chevreuil - Kaisen',
		],	
		[
			'title' => 'Kaisen Linux 20200211 Release Notes',
			'extract' => 'This new release is revision of version 20200206. Minors fix. Minors updates. Menus reworked.',
			'date'=> '2020/04/03',
			'visuel' => '/img/blog/screensr.png',
			'link' => 'kaisenlinux20200211.php',
			'author' => 'Kevin Chevreuil - Kaisen',
		],	
		[
			'title' => 'Kaisen Linux 20200212 Release Notes',
			'extract' => 'This new release is revision of version 20200211. Added tools. Adapting to Debian 10.3. Minor update.',
			'date'=> '2020/04/03',
			'visuel' => '/img/blog/screensr.png',
			'link' => 'kaisenlinux20200212.php',
			'author' => 'Kevin Chevreuil - Kaisen',
		],	
		[
			'title' => 'Kaisen Linux 20200217 Release Notes',
			'extract' => 'This new release is revision of version 20200212. Added tools. New logo. Menus reworked.',
			'date'=> '2020/04/03',
			'visuel' => '/img/blog/screensr.png',
			'link' => 'kaisenlinux20200217.php',
			'author' => 'Kevin Chevreuil - Kaisen',
		],	

		[
			'title' => 'Kaisen Linux 20200224 Release Notes',
			'extract' => 'This new release is revision of version 20200217. Conky reworked (color). Lots of tools added (+70 tools).',
			'date'=> '2020/04/03',
			'visuel' => '/img/blog/screensr.png',
			'link' => 'kaisenlinux20200224.php',
			'author' => 'Kevin Chevreuil - Kaisen',
		],	
		[
			'title' => 'Kaisen Linux 20200301 Release Notes',
			'extract' => 'This new release is revision of version 20200224. Plymouth theme added (bootsplash). Boot entries in ISO reworked.',
			'date'=> '2020/04/03',
			'visuel' => '/img/blog/screensr.png',
			'link' => 'kaisenlinux20200301.php',
			'author' => 'Kevin Chevreuil - Kaisen',
		],	
		[
			'title' => 'Kaisen Linux 20200304 Release Notes',
			'extract' => 'This new release is revision of version 20200301. The exfat filesystem is now supported. Important bug fixed.',
			'date'=> '2020/04/03',
			'visuel' => '/img/blog/screensr.png',
			'link' => 'kaisenlinux20200304.php',
			'author' => 'Kevin Chevreuil - Kaisen',
		],	

		[
			'title' => 'Kaisen Linux 20200307 Release Notes',
			'extract' => 'This new release is revision at 20200304 version. This version delivers more tools to manage filesystems.',
			'date'=> '2020/04/03',
			'visuel' => '/img/blog/screensr.png',
			'link' => 'kaisenlinux20200307.php',
			'author' => 'Kevin Chevreuil - Kaisen',
		],	

		[
			'title' => 'Kaisen Linux 20200325 Release Notes',
			'extract' => 'This new release is revision at 20200307 release. This version comes with new things on the GUI.',
			'date'=> '2020/04/03',
			'visuel' => '/img/blog/screensr.png',
			'link' => 'kaisenlinux20200325.php',
			'author' => 'Kevin Chevreuil - Kaisen',
		],	

		[
			'title' => 'Kaisen Linux 20200413 Release Notes',
			'extract' => 'This new release is revision at 20200325 release. This version is a final beta version. This is the version before rolling.',
			'date'=> '2020/04/17',
			'visuel' => '/img/blog/screensr.png',
			'link' => 'kaisenlinux20200413.php',
			'author' => 'Kevin Chevreuil - Kaisen',
		],	
		[
			'title' => 'Kaisen Linux Rolling 1.0 release note',
			'extract' => 'This first stable version. Continuous updating thanks to the repository and custom packages.',
			'date'=> '2020/05/19',
			'visuel' => '/img/blog/screensr.png',
			'link' => 'kaisenlinuxrolling1.0.php',
			'author' => 'Kevin Chevreuil - Kaisen',
		],	
		[
			'title' => 'Kaisen Linux Rolling 1.1 release note',
			'extract' => 'Rolling revision. Fix a lot of bad construction and added new tools. New logo and new wallpapers.',
			'date'=> '2020/06/15',
			'visuel' => '/img/blog/screen-1.1.x.png',
			'link' => 'kaisenlinuxrolling1.1.php',
			'author' => 'Kevin Chevreuil - Kaisen',
		],	
		[
			'title' => 'Kaisen Linux Rolling 1.2 release note',
			'extract' => 'New revision of the rolling. Lots of work. GUI news. New translations. New file systems supported.',
			'date'=> '2020/07/23',
			'visuel' => '/img/blog/screen-1.1.x.png',
			'link' => 'kaisenlinuxrolling1.2.php',
			'author' => 'Kevin Chevreuil - Kaisen',
		],	
		[
			'title' => 'Kaisen Linux Rolling 1.3 release note',
			'extract' => 'New revision of the rolling. Almost complete overhaul of the system. New tools and new conky.',
			'date'=> '2020/08/20',
			'visuel' => '/img/blog/screen-1.1.x.png',
			'link' => 'kaisenlinuxrolling1.3.php',
			'author' => 'Kevin Chevreuil - Kaisen',
		],	
		[
			'title' => 'Kaisen Linux Rolling 1.4 release note',
			'extract' => 'New revision of the rolling. End summer release. New tools and renew conky. Bugs fixed.',
			'date'=> '2020/08/30',
			'visuel' => '/img/blog/screen-1.1.x.png',
			'link' => 'kaisenlinuxrolling1.4.php',
			'author' => 'Kevin Chevreuil - Kaisen',
		],	
		[
			'title' => 'Kaisen Linux Rolling 1.5 release note',
			'extract' => 'New revision of the rolling. Lot of ameliorations. New tools and design. Bugs fixed.',
			'date'=> '2020/12/13',
			'visuel' => '/img/blog/screen-1.1.x.png',
			'link' => 'kaisenlinuxrolling1.5.php',
			'author' => 'Kevin Chevreuil - Kaisen',
		],
		[
            'title' => 'Kaisen Linux Rolling 1.6 release note',
        	'extract' => 'New revision of the rolling. Lot of ameliorations. New tools and new conky. Bugs fixed.',
            'date'=> '2021/03/31',
            'visuel' => '/img/blog/screen-1.1.x.png',
            'link' => 'kaisenlinuxrolling1.6.php',
            'author' => 'Kevin Chevreuil - Kaisen',
        ],
		[
            'title' => 'Kaisen Linux Rolling 1.7 release note',
        	'extract' => 'New revision of the rolling. Final 1.1.x release. Lot of ameliorations. New ISOS.',
            'date'=> '2021/07/19',
            'visuel' => '/img/blog/screen-1.1.x.png',
            'link' => 'kaisenlinuxrolling1.7.php',
            'author' => 'Kevin Chevreuil - Kaisen',
        ],
		[
            'title' => 'Kaisen Linux Rolling 1.8 release note',
        	'extract' => 'New revision of the rolling. Real final 1.1.x release. Revision of the NETINST ISO.',
            'date'=> '2021/08/04',
            'visuel' => '/img/blog/screen-1.1.x.png',
            'link' => 'kaisenlinuxrolling1.8.php',
            'author' => 'Kevin Chevreuil - Kaisen',
        ],
		[
            'title' => 'Kaisen Linux Rolling 2.0 release note',
        	'extract' => 'New revsion of the rolling. First 2.x releases. Major bugs fixed. Lots of improvements.',
            'date'=> '2021/12/14',
            'visuel' => '/img/blog/screen-1.1.x.png',
            'link' => 'kaisenlinuxrolling2.0.php',
            'author' => 'Kevin Chevreuil - Kaisen',
        ],

		[
            'title' => 'Kaisen Linux Rolling 2.1 release note',
                'extract' => 'Lots of improvements on the design. New cloud and tech tools. Improvements of the packages and confs.',
            'date'=> '2022/06/14',
            'visuel' => '/img/blog/screen-2.1.x.png',
            'link' => 'kaisenlinuxrolling2.1.php',
            'author' => 'Kevin Chevreuil - Kaisen',
        ],

		[
            'title' => 'Kaisen Linux Rolling 2.2 release note',
                'extract' => 'The three years old release. Minor bugs fixed. Many improvements of the GUI. Adding the exegol tool!',
            'date'=> '2022/12/14',
            'visuel' => '/img/blog/screen-2.1.x.png',
            'link' => 'kaisenlinuxrolling2.2.php',
            'author' => 'Kevin Chevreuil - Kaisen',
        ],

                [
            'title' => 'Kaisen Linux Rolling 2.3 release note',
                'extract' => 'The latest version of the 2.x serie. Major and minor bugs fixed. Immutables snapshots. New cloud tools.',
            'date'=> '2023/05/29',
            'visuel' => '/img/blog/screen-2.1.x.png',
            'link' => 'kaisenlinuxrolling2.3.php',
            'author' => 'Kevin Chevreuil - Kaisen',
        ],
                [
            'title' => 'Kaisen Linux Rolling 3.0 release note',
                'extract' => 'The ultime and the last release of Kaisen Linux. Major and minor bugs fixed. End of the project whis this release.',
            'date'=> '2025/08/13',
            'visuel' => '/img/blog/screen-3.0.jpg',
            'link' => 'kaisenlinuxrolling3.0.php',
            'author' => 'Kevin Chevreuil - Kaisen',
        ],

	];

	$blog = array_reverse($blog);

?>
